site_name: Slim Framework
pages:
    - [index.md, Home]
    - [start/installation.md, Get Started, Installation]
    - [architecture.md, Get Started, Architecture]
    - [lifecycle.md, Get Started, Lifecycle]
    - [objects/environment.md, Objects, Environment]
    - [objects/request.md, Objects, Request]
    - [objects/response.md, Objects, Response]
    - [objects/router.md, Objects, Router]
    - [view.md, Features, View]
    - [middleware.md, Middleware]
    - [session.md, Session]
    - [caching.md, Caching]
    - [hooks.md, Hooks]
    - [errors.md, Error Handling]
    - [configuration.md, Configuration]
    - [interface_collection.md, Interfaces, Collection]
    - [contributors/guidelines.md, Contributors, Guidelines]
    - [contributors/strategy.md, Contributors, Branching Strategy]
theme: readthedocs
markdown_extensions: [markdown.extensions.extra]
